version: '2'
services:
    crm-app:
        image: crm
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://crm-postgresql:5432/crm
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://crm-elasticsearch:9200
        ports:
            - 8080:8080
    crm-postgresql:
        extends:
            file: postgresql.yml
            service: crm-postgresql
    crm-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: crm-elasticsearch
